default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=50000']
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending

  # - repo: https://github.com/psf/black
  #   rev: 23.9.1
  #   hooks:
  #     - id: black

  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.7.0
  #   hooks:
  #     - id: nbqa-black
  #       additional_dependencies: [black==23.9.1]
  #     - id: nbqa-isort
  #       additional_dependencies: [isort==5.12.0]
  #     - id: nbqa-flake8
  #       additional_dependencies: [flake8==3.9.2]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.3
  #   hooks:
  #     - id: prettier
  #       types_or: [markdown, yaml, toml, json, dockerfile, shell]
